version: "3.8"

services:
  scheduler:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: job_scheduler
    working_dir: /app
    volumes:
      - ../:/app
    command: node apps/scheduler/index.js
    shm_size: "2gb"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  telegram-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: job_telegram_bot
    working_dir: /app
    volumes:
      - ../:/app
    command: node apps/telegram/start.js
    shm_size: "2gb"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
