const axios = require("axios");
const config = require("../config");
const logger = require("../logger");

class AiOrchestrator {
    constructor() {
        this.apiKey = config.ai.openRouterKey;
        this.model = config.ai.model;
    }

    /**
     * Translates a natural language prompt into a structured JSON task
     * @param {string} commandText 
     * @returns {Promise<{plugin: string, action: string, args: {keywords?: string, location?: string}}>}
     */
    async parseCommand(commandText) {
        logger.info(`Parsing command with AI Orchestrator: "${commandText}"`, { action: "parse_command" });

        if (!this.apiKey) {
            logger.warn("OpenRouter API Key not set. Using local rule-based parsing fallback.");
            return this.ruleBasedFallback(commandText);
        }

        try {
            const systemPrompt = `
You are the orchestration AI for an autonomous job application automation platform. 
Your task is to parse a natural language command into a structured action object.

Available plugins/portals:
- naukri
- linkedin
- foundit
- hirist
- instahyre

Available actions:
- login: Navigates to page and authenticates.
- updateProfile: Triggers profile update tasks (e.g. edits resume headline).
- apply: Searches for jobs and automatically runs application routines.

Format your output as a single valid JSON object. DO NOT wrap it in markdown code blocks like \`\`\`json. Return only the JSON string.
Structure:
{
  "plugin": "naukri" | "linkedin" | "foundit" | "hirist" | "instahyre",
  "action": "login" | "updateProfile" | "apply",
  "args": {
    "keywords": "job search keywords (default 'Software Engineer')",
    "location": "location filter (default '')"
  }
}
`;

            const response = await axios.post(
                "https://openrouter.ai/api/v1/chat/completions",
                {
                    model: this.model,
                    messages: [
                        { role: "system", content: systemPrompt },
                        { role: "user", content: commandText }
                    ],
                    temperature: 0.1
                },
                {
                    headers: {
                        Authorization: `Bearer ${this.apiKey}`,
                        "Content-Type": "application/json"
                    },
                    timeout: 15000
                }
            );

            let content = response.data.choices[0].message.content.trim();
            // Safe clean of markdown blocks if generated by model
            if (content.startsWith("```")) {
                content = content.replace(/^```json\s*/i, "").replace(/```$/, "").trim();
            }
            
            const parsed = JSON.parse(content);
            logger.info(`AI Orchestration completed successfully: ${JSON.stringify(parsed)}`, { action: "parse_command", success: true });
            return parsed;
        } catch (error) {
            logger.error(`AI Orchestration service error: ${error.message}. Running rule fallback.`, { action: "parse_command", success: false });
            return this.ruleBasedFallback(commandText);
        }
    }

    /**
     * Local regex fallback parser
     * @param {string} commandText 
     */
    ruleBasedFallback(commandText) {
        const text = commandText.toLowerCase();
        
        let plugin = "naukri";
        if (text.includes("linkedin")) plugin = "linkedin";
        else if (text.includes("foundit")) plugin = "foundit";
        else if (text.includes("hirist")) plugin = "hirist";
        else if (text.includes("instahyre")) plugin = "instahyre";

        let action = "apply";
        if (text.includes("login") || text.includes("log in") || text.includes("signin") || text.includes("sign in")) {
            action = "login";
        } else if (text.includes("update") || text.includes("profile") || text.includes("refresh")) {
            action = "updateProfile";
        }

        let keywords = "Software Engineer";
        let location = "";

        // Keyword extraction regex
        const kwMatch = text.match(/(?:apply|search|find)\s+(?:only\s+)?(.*?)(?:\s+jobs)?(?:\s+in\s+|\s+at\s+|$)/i);
        if (kwMatch && kwMatch[1]) {
            let val = kwMatch[1].trim();
            val = val.replace(/\b(?:only|for|to|on)\b/g, "").replace(/\s+/g, " ").trim();
            if (val && !["devops jobs", "developer jobs", "engineer jobs", "jobs"].includes(val)) {
                keywords = val;
            }
        }
        
        // Location extraction regex
        const locMatch = text.match(/(?:in|at|location)\s+([a-zA-Z\s]+)/i);
        if (locMatch && locMatch[1]) {
            let val = locMatch[1].trim();
            // Clean up suffix portal text (e.g. "on naukri", "on linkedin")
            val = val.replace(/\s+on\s+(?:naukri|linkedin|foundit|hirist|instahyre)\s*$/gi, "");
            location = val.trim();
        }

        const result = {
            plugin,
            action,
            args: { keywords, location }
        };

        logger.info(`Local parsing fallback outcome: ${JSON.stringify(result)}`, { action: "parse_command_fallback" });
        return result;
    }
}

module.exports = new AiOrchestrator();
